/**
 * `aicek init` core (PRD Stage 3) — pure generation. Builds the file contents
 * and a write-plan from a detected inventory + selected marketplace entries.
 * NO filesystem writes here: the CLI owns I/O, so this stays testable and the
 * read-only/dry-run guarantees are trivial to honor.
 */
import type { ConfigInventory } from "./types.js";
import { type RegistryEntry, findEntry } from "./registry.js";
import { tokensOf } from "./estimate.js";

/** Curated presets that pre-select marketplace entries by use-case. */
export interface InitProfile {
  id: string;
  label: string;
  entries: string[];
}

export const PROFILES: readonly InitProfile[] = [
  { id: "minimal", label: "Minimal — clean CLAUDE.md + ignore, no extras", entries: [] },
  { id: "frontend", label: "Frontend — design + up-to-date docs", entries: ["Impeccable", "Context7"] },
  { id: "full-stack", label: "Full-stack — planning, docs, review", entries: ["OpenSpec", "Context7", "Code Review Skill"] },
  { id: "token-optimizer", label: "Token Optimizer — compression + targeted context", entries: ["Caveman", "Graphify"] },
];

export type FileAction = "create" | "overwrite";

export interface PlannedFile {
  path: string;
  content: string;
  action: FileAction;
}

export interface InstallStep {
  name: string;
  owner: string;
  install_type: RegistryEntry["install_type"];
  command: string;
}

export interface InitPlan {
  selected: RegistryEntry[];
  files: PlannedFile[];
  installs: InstallStep[];
  credits: string[];
  /** Estimated tokens added to always-on context by the generated CLAUDE.md. */
  estClaudeMdTokens: number;
}

const IGNORE_BY_STACK: Record<string, string[]> = {
  node: ["node_modules/", "dist/", "*.log", ".env", ".env.*"],
  python: ["__pycache__/", "*.pyc", ".venv/", "venv/", ".env"],
  go: ["bin/", "*.exe", "vendor/"],
  rust: ["target/"],
  java: ["target/", "build/", "*.class"],
  ruby: ["vendor/bundle/", "*.gem", ".env"],
  php: ["vendor/", ".env"],
};

/** Build a .gitignore body from the detected stack(s). */
export function generateIgnore(stack: string[]): string {
  const lines = new Set<string>([".DS_Store", "Thumbs.db"]);
  for (const s of stack) for (const l of IGNORE_BY_STACK[s] ?? []) lines.add(l);
  return "# Generated by aicek\n" + [...lines].join("\n") + "\n";
}

/** Build a clean, minimal CLAUDE.md. Attribution for installed entries is included. */
export function generateClaudeMd(stack: string[], selected: RegistryEntry[]): string {
  const L: string[] = [];
  L.push("# Project");
  L.push("");
  L.push("> Starter generated by aicek. Keep this short and always-relevant —");
  L.push("> procedural how-tos belong in skills; path-specific rules in .claude/rules.");
  L.push("");
  L.push("## Stack");
  if (stack.length) for (const s of stack) L.push(`- ${s}`);
  else L.push("- (add your stack)");
  L.push("");
  L.push("## Conventions");
  L.push("- (add always-relevant project conventions here)");
  L.push("");
  if (selected.length) {
    L.push("## Installed tools");
    L.push("");
    for (const e of selected) {
      L.push(`- ${e.name} by ${e.owner} — ${e.category}. ${e.repo_url}`);
    }
    L.push("");
  }
  return L.join("\n");
}

/** Attribution lines for the selected entries (PRD §5.7: always credit owners). */
export function attributionFor(selected: RegistryEntry[]): string[] {
  return selected
    .filter((e) => e.attribution_required)
    .map((e) => `${e.name} by ${e.owner} — ${e.repo_url} (${e.license ?? "see repo"})`);
}

/**
 * Compute the init write-plan. Pure: returns the files that WOULD be written and
 * the install steps that WOULD run, without touching disk.
 */
export function planInit(inventory: ConfigInventory, selectedNames: string[]): InitPlan {
  const selected = selectedNames
    .map((n) => findEntry(n))
    .filter((e): e is RegistryEntry => Boolean(e));

  const claudeMdContent = generateClaudeMd(inventory.stack, selected);
  const ignoreContent = generateIgnore(inventory.stack);

  const hasIgnore = inventory.ignoreFiles.some((f) => f.path.endsWith(".gitignore"));

  const files: PlannedFile[] = [
    {
      path: "CLAUDE.md",
      content: claudeMdContent,
      action: inventory.claudeMd ? "overwrite" : "create",
    },
    {
      path: ".gitignore",
      content: ignoreContent,
      action: hasIgnore ? "overwrite" : "create",
    },
  ];

  const installs: InstallStep[] = selected.map((e) => ({
    name: e.name,
    owner: e.owner,
    install_type: e.install_type,
    command: e.install_command,
  }));

  return {
    selected,
    files,
    installs,
    credits: attributionFor(selected),
    estClaudeMdTokens: tokensOf(claudeMdContent),
  };
}
