/**
 * Shareable report renderers (PRD Stage 4). Pure: audit → string. The CLI writes
 * the result to a file. No runtime deps — HTML and SVG are built as strings so
 * `doctor --html` / `doctor --share` work with zero image toolchain.
 */
import type { AuditArtifact, PillarName } from "./types.js";

const PILLAR_LABEL: Record<PillarName, string> = {
  "context-economy": "Context Economy",
  "routing-correctness": "Routing Correctness",
  "skill-effectiveness": "Skill Effectiveness",
  "structural-hygiene": "Structural Hygiene",
  "redundancy-overlap": "Redundancy & Overlap",
};

function gradeFor(score: number): string {
  if (score >= 90) return "EXCELLENT";
  if (score >= 80) return "GOOD";
  if (score >= 60) return "FAIR";
  if (score >= 40) return "POOR";
  return "CRITICAL";
}

function colorFor(ratio: number): string {
  if (ratio >= 0.8) return "#22c55e";
  if (ratio >= 0.6) return "#eab308";
  return "#ef4444";
}

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** A self-contained HTML report (inline CSS, no assets). */
export function renderHtml(a: AuditArtifact): string {
  const color = colorFor(a.healthScore / 100);
  const pillars = a.pillars
    .map((p) => {
      const pct = p.max === 0 ? 100 : Math.round((p.score / p.max) * 100);
      const c = colorFor(p.max === 0 ? 1 : p.score / p.max);
      return `<div class="pillar"><div class="row"><span>${esc(PILLAR_LABEL[p.pillar])}</span><span>${p.score}/${p.max}</span></div><div class="track"><div class="bar" style="width:${pct}%;background:${c}"></div></div></div>`;
    })
    .join("\n");
  const recs = a.recommendations
    .slice(0, 10)
    .map(
      (r) =>
        `<li><span class="sev sev-${r.severity}">${r.severity}</span> ${esc(r.fix)} <span class="muted">(+${r.estHealthGain.points}${r.estTokenSaving.value ? `, ~${r.estTokenSaving.value} tok` : ""})</span></li>`,
    )
    .join("\n");
  const estimates = a.estimates
    .map((e) => `<li>${esc(e.name)}: <strong>${e.value}</strong> tok <span class="muted">(${e.confidence})</span></li>`)
    .join("\n");

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>aicek doctor — health ${a.healthScore}/100</title>
<style>
  :root{color-scheme:dark}
  body{margin:0;background:#0b0f17;color:#e5e7eb;font:16px/1.5 ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,sans-serif}
  .wrap{max-width:760px;margin:0 auto;padding:48px 24px}
  h1{font-size:14px;letter-spacing:.18em;text-transform:uppercase;color:#9ca3af;margin:0 0 8px}
  .score{font-size:72px;font-weight:800;line-height:1;color:${color}}
  .grade{font-weight:700;color:${color};margin-left:8px;font-size:18px;vertical-align:super}
  .muted{color:#6b7280}
  h2{font-size:13px;letter-spacing:.12em;text-transform:uppercase;color:#9ca3af;margin:36px 0 12px}
  .pillar{margin:10px 0}.row{display:flex;justify-content:space-between;font-size:14px;margin-bottom:4px}
  .track{height:8px;background:#1f2937;border-radius:6px;overflow:hidden}.bar{height:100%}
  ul{list-style:none;padding:0;margin:0}li{padding:8px 0;border-bottom:1px solid #1f2937;font-size:14px}
  .sev{font-weight:700;font-size:12px;padding:1px 6px;border-radius:4px;margin-right:6px}
  .sev-P0{background:#7f1d1d;color:#fecaca}.sev-P1{background:#7c2d12;color:#fed7aa}.sev-P2{background:#713f12;color:#fde68a}.sev-P3{background:#1f2937;color:#9ca3af}
  footer{margin-top:40px;color:#6b7280;font-size:13px}
  a{color:#60a5fa}
</style></head>
<body><div class="wrap">
  <h1>aicek doctor · configuration health</h1>
  <div><span class="score">${a.healthScore}</span><span class="muted" style="font-size:28px">/100</span><span class="grade">${gradeFor(a.healthScore)}</span></div>
  <h2>Pillars</h2>
  ${pillars}
  <h2>Top recommendations</h2>
  <ul>${recs || "<li class='muted'>No issues found.</li>"}</ul>
  <h2>Estimates <span class="muted">(every number is an estimate)</span></h2>
  <ul>${estimates}</ul>
  <footer>Generated by <a href="https://github.com/HemVaria/aicek">aicek</a> · schema v${a.schemaVersion}, engine v${a.engineVersion} · Read-only. Install less. Use better. Measure everything.</footer>
</div></body></html>
`;
}

/** A shareable SVG health-score card (1200×630 social ratio). */
export function renderShareSvg(a: AuditArtifact): string {
  const color = colorFor(a.healthScore / 100);
  const grade = gradeFor(a.healthScore);
  const bars = a.pillars
    .map((p, i) => {
      const w = (p.max === 0 ? 1 : p.score / p.max) * 320;
      const c = colorFor(p.max === 0 ? 1 : p.score / p.max);
      const y = 250 + i * 58;
      return `<text x="80" y="${y - 8}" fill="#9ca3af" font-size="20" font-family="sans-serif">${esc(PILLAR_LABEL[p.pillar])}</text>
  <rect x="80" y="${y}" width="320" height="14" rx="7" fill="#1f2937"/>
  <rect x="80" y="${y}" width="${w.toFixed(1)}" height="14" rx="7" fill="${c}"/>`;
    })
    .join("\n  ");

  return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630">
  <rect width="1200" height="630" fill="#0b0f17"/>
  <text x="80" y="90" fill="#9ca3af" font-size="26" letter-spacing="6" font-family="sans-serif">AICEK · CONFIGURATION HEALTH</text>
  <text x="760" y="300" fill="${color}" font-size="280" font-weight="800" font-family="sans-serif">${a.healthScore}</text>
  <text x="760" y="360" fill="#6b7280" font-size="48" font-family="sans-serif">/100</text>
  <text x="760" y="430" fill="${color}" font-size="44" font-weight="700" font-family="sans-serif">${grade}</text>
  ${bars}
  <text x="80" y="590" fill="#6b7280" font-size="24" font-family="sans-serif">npx aicek doctor   ·   #aicek</text>
</svg>
`;
}
